# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: dialogflow_grpc
description: Flutter package for Dialogflow CX, V2 and V2beta using gRPC. A faster integration with the Dialogflow API and also the possibility to do audio streaming.
version: 0.2.9
homepage: https://www.leeboonstra.dev
repository: https://github.com/savelee/dialogflow_grpc_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  uuid: ^3.0.1
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.leeboonstra.dialogflow_grpc
        pluginClass: DialogflowGrpcPlugin
      ios:
        pluginClass: DialogflowGrpcPlugin
      macos:
        pluginClass: DialogflowGrpcPlugin
      windows:
        pluginClass: DialogflowGrpcPlugin
      linux:
        pluginClass: DialogflowGrpcPlugin
  